name: libpythonproGabriel-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main

jobs:
  build:
    env:
      GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres12
        env:

steps:

- uses: actions/checkout@v2

- name: Set up Python 3.10.3

uses: actions/setup-python@v2

with:

python-version: 3.10.3

- name: Install dependencies

run: |

python -m pip install --upgrade pip

pip install -r requirements-dev.txt

- name: Lint with flake8

run: |

flake8 .