name: libGabriel

on: [ push ]
run on

jobs:

 build:

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architeture: x64
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Rodar flake8
      uses: py-actions/flake8
      with:
        checkName: 'flake8_py3' 
    - name: Rodar Testes Automaticos
      run: |
        pytest libpythonpro --cov=libpythonpro
    - name: Relatório Coverage
      env:
        CODE_TOKEN: "TOKEN_CODECOV"
      run: |
        codecov
